### ISSUE TITLE
missing file webcams.json.tmpl

### ISSUE THREAD

**Issue by KillerBeagle** [motion-ai/motion-ai#1]
Two places in the quickstart guide refer to a template file webcams.json.tmpl; however, that file doesn't exist as far as I can tell.

**Comment by dcmartin** [comment]
There is no longer a need for the template file; if you could point me at the documentation that would help to fix it.

**Comment by KillerBeagle** [comment]
https://github.com/motion-ai/motion-ai/blob/master/docs/QUICKSTART.md

**Comment by KillerBeagle** [comment]
If there is a better quickstart guide for AMD64 / Ubuntu 18.04 please let me know

**Comment by dcmartin** [comment]
Development branch (more current) is at github.com/dcmartin/motion-ai

**Comment by dcmartin** [comment]
It's no longer required; git pull.
